const INITIAL_STATE ={ 
  SHOP_DATA:{
  hats:{
    id: 1,
    title: 'Hats',
    routeName: 'hats',
    items: [
      {
        id: "0195153448",
        name: "Classical Mythology",
        Author: "Mark P. O. Morford",
        Year_of_publication: 2002,
        Publisher: "Oxford University Press",
        imageUrl_s: "http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0195153448',
        descreption:"Building on the bestselling tradition of previous editions, Classical Mythology, Tenth Edition, is the most comprehensive survey of classical mythology available--and the first full-color textbook of its kind. Featuring the authors' clear and extensive translations of original sources, it brings to life the myths and legends of Greece and Rome in a lucid and engaging style. The text contains a wide variety of faithfully translated passages from Greek and Latin sources, including Homer, Hesiod, all the Homeric Hymns, Pindar, Aeschylus, Sophocles, Euripides, Herodotus, Plato, Lucian, Lucretius, Vergil, Ovid, and Seneca.Acclaimed authors Mark P.O. Morford, Robert J. Lenardon, and Michael Sham incorporate a dynamic combination of poetic narratives and enlightening commentary to make the myths come alive for students. Offering historical and cultural background on the myths (including evidence from art and archaeology) they also provide ample interpretative material and examine the enduring survival of classical mythology and its influence in the fields of art, literature, music, dance, and film."
      },
      {
        id: "0002005018",
        name: "Clara Callan",
        Author: "Richard Bruce Wright",
        Year_of_publication: 2001,
        Publisher: "HarperFlamingo Canada",
        imageUrl_s: "http://images.amazon.com/images/P/0002005018.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0002005018.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0002005018',
        descreption:"It is the story of a women in her thirties living in ontario during 1930s and is written in epistolary form, utilizing letters and journal entries to tell the story."
      },
      {
        id: "0060973129",
        name: "Decision in Normandy",
        Author: "Carlo D'Este",
        Year_of_publication: 1991,
        Publisher: "HarperPerennial",
        imageUrl_s: "http://images.amazon.com/images/P/0060973129.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060973129.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0060973129',
        descreption:"The battle of Normandy was the most complex and daring military operations in the history of modern warfare. Two years of intense, detailed planning reached its successful conclusion when the Allied forces took to the beaches on D-Day."
      },
      {
        id: "0374157065",
        name: "Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It",
        Author: "Gina Bari Kolata",
        Year_of_publication: 1999,
        Publisher: "Farrar Straus Giroux",
        imageUrl_s: "http://images.amazon.com/images/P/0374157065.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0374157065.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0374157065',
        descreption:"It was a plague so deadly that if a similar virus were to strike today, it would kill more people in a single year than heart disease, cancers, strokes, chronic pulmonary disease, AIDS and Alzheimer's disease combined."
      },
      {
        id: "0393045218",
        name: "The Mummies of Urumchi",
        Author: "E. J. W. Barber",
        Year_of_publication: 1999,
        Publisher: "W. W. Norton &amp; Company",
        imageUrl_s: "http://images.amazon.com/images/P/0393045218.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0393045218.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0393045218',
        descreption:"In the museums of Ürümchi, the windswept regional capital of the Uyghur Autonomous Region (also known as Chinese Turkestan), a collection of ancient mummies lies at the center of an enormous mystery."
      },
      {
        id: "0399135782",
        name: "The Kitchen God's Wife",
        Author: "Amy Tan",
        Year_of_publication: 1991,
        Publisher: "Putnam Pub Group",
        imageUrl_s: "http://images.amazon.com/images/P/0399135782.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0399135782.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0399135782.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0399135782',
        descreption:"The Kitchen God's Wife is the second novel by Chinese-American author, Amy Tan. First published in 1991, it deals extensively with Sino-American female identity and draws on the story of her mother's life. The book was largely considered a commercial success, making best sellers lists in several countries worldwide."
      },
      {
        id: "0425176428",
        name: "What If?: The World's Foremost Military Historians Imagine What Might Have Been",
        Author: "Robert Cowley",
        Year_of_publication: 2000,
        Publisher: "Berkley Publishing Group",
        imageUrl_s: "http://images.amazon.com/images/P/0425176428.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0425176428.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0425176428',
        descreption:"It is an anthology of twenty essays and fourteen sidebars dealing with counterfactual history,  Cowley decided to create the book after several articles were published in the Military History Quarterly, which he edits, and received a lot of attention."
      },
      {
        id: "0671870432",
        name: "PLEADING GUILTY",
        Author: "Scott Turow",
        Year_of_publication: 1993,
        Publisher: "Audioworks",
        imageUrl_s: "http://images.amazon.com/images/P/0671870432.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0671870432.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0671870432.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0671870432',
        descreption:"Mack Malloy, ex-cop, not-quite-ex-drunk, and partner-on-the-wane in one of the country's most high-powered law firms. A long-time ally of the wayward, Mack is on the trail of a colleague, his firm's star litigator, who has vanished with more than five million dollars of a client's money."
      },
      {
        id: "0679425608",
        name: "Under the Black Flag: The Romance and the Reality of Life Among the Pirates",
        Author: "David Cordingly",
        Year_of_publication: 1996,
        Publisher: "Random House",
        imageUrl_s: "http://images.amazon.com/images/P/0679425608.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0679425608.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0679425608.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0679425608',
        descreption:"Pirates are so much a part of legend that it is easy to forget they actually existed. UNDER THE BLACK FLAG tells their story in a rollicking account of the golden age of piracy that is packed with history, anecdote, and above all adventure. Here are the true stories of such bloodthirsty legends as Blackbeard and Captain Kidd."
      },
      {
        id: "074322678X",
        name: "Where You'll Find Me: And Other Stories",
        Author: "Ann Beattie",
        Year_of_publication: 2002,
        Publisher: "Scribner",
        imageUrl_s: "http://images.amazon.com/images/P/074322678X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/074322678X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/074322678X',
        descreption:"Where You'll Find Me and Other Stories by Ann Beattie is a collection of short stories full of suspense and nostalgia. ... The author greatly stresses her love and appreciation to the city, it's people, and culture through different characters in different stories."
      },
      {
        id: "0771074670",
        name: "Nights Below Station Street",
        Author: "David Adams Richards",
        Year_of_publication: 1988,
        Publisher: "Emblem Editions",
        imageUrl_s: "http://images.amazon.com/images/P/0771074670.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0771074670.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0771074670',
        descreption:"The novel centres on the Walshes, a rural New Brunswick family in the 1970s.[1] Patriarch Joe has been only irregularly employed since injuring his back at work several years earlier, his wife Rita is concerned about his resulting struggles with alcoholism and depression."
      },
      {
        id: "080652121X",
        name: "Hitler's Secret Bankers: The Myth of Swiss Neutrality During the Holocaust",
        Author: "Adam Lebor",
        Year_of_publication: 2000,
        Publisher: "Citadel Press",
        imageUrl_s: "http://images.amazon.com/images/P/080652121X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/080652121X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/080652121X',
        descreption:"No death certificates were issued at Auschwitz, but today Swiss bankers still demand them before they will release to relatives the assets of account holders killed in the Holocaust. Based on newly declassified documents and archival research, Hitler's Secret Banks reveals the full, hitherto unknown extent of Swiss economic collaboration with the Nazis."
      },
      {
        id: "0887841740",
        name: "The Middle Stories",
        Author: "Sheila Heti",
        Year_of_publication: 2004,
        Publisher: "House of Anansi Press",
        imageUrl_s: "http://images.amazon.com/images/P/0887841740.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0887841740.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0887841740.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/0887841740',
        descreption:"it is where the bulk of the story rests. It explains the topic, gives important key details, and holds the reader's attention, but most importantly it is where we reach the climax or turning point of the story."
      },
      {
        id: "1552041778",
        name: "Jane Doe",
        Author: "R. J. Kaiser",
        Year_of_publication: 1999,
        Publisher: "Mira Books",
        imageUrl_s: "http://images.amazon.com/images/P/1552041778.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1552041778.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1552041778.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/1552041778',
        descreption:"Victoria Helen Stone's biting thriller centers around a woman whose sole motivation is revenge, there are no false pretenses or veiled motivations here; Jane has revenge on the brain, and she won't stop until she gets what she wants."
      },
      {
        id: "1558746218",
        name: "A Second Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series)",
        Author: "Jack Canfield",
        Year_of_publication: 1998,
        Publisher: "Health Communications",
        imageUrl_s: "http://images.amazon.com/images/P/1558746218.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1558746218.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/1558746218',
        descreption:"This latest collection of stories celebrates the shared experiences of being a woman in a 101 new ways. You will be moved by these true accounts of how women like you have embraced life's defining moments by finding love, dealing with loss, overcoming obstacles and achieving their dreams and goals."
      },
      {
        id: "1567407781",
        name: "The Witchfinder (Amos Walker Mystery Series)",
        Author: "Loren D. Estleman",
        Year_of_publication: 1998,
        Publisher: "Brilliance Audio - Trade",
        imageUrl_s: "http://images.amazon.com/images/P/1567407781.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1567407781.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1567407781.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/1567407781',
        descreption:"Jay has never forgotten the photo once sent to him of his young fiancee - naked in the arms of another man. Now on his deathbed and convinced the photo was a fake, the hunt is on for a modern-day witchfinder. And Amos Walker is the man for the job."
      },
      {
        id: "1575663937",
        name: "More Cunning Than Man: A Social History of Rats and Man",
        Author: "Robert Hendrickson",
        Year_of_publication: 1999,
        Publisher: "Kensington Publishing Corp.",
        imageUrl_s: "http://images.amazon.com/images/P/1575663937.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1575663937.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1575663937.01.LZZZZZZZ.jpg",
        linkUrl:'/hats/1575663937',
        descreption:"Filled with rat attack stories, strange tales of elderly women living with rats, and other interesting information, a fascinating foray into the world of the rat examines the way these creatures have survived through the ages despite many attempts to annihilate them."
      },


    ]
  },
  sneakers:{
    id: 2,
    title: 'Sneakers',
    routeName: 'sneakers',
    items: [
      {
        id: "0375410538",
        name: "Anil's Ghost",
        Author: "MICHAEL ONDAATJE",
        Year_of_publication: 2000,
        Publisher: "Knopf",
        imageUrl_s: "http://images.amazon.com/images/P/0375410538.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0375410538.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0375410538.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0375410538',
        descreption:"It is the critically acclaimed fourth novel by Michael Ondaatje, Anil's Ghost follows the life of Anil Tissera, a native Sri Lankan who left to study in Britain and then the United States on a scholarship, during which time she has become a forensic pathologist."
      },
      {
        id: "0966986105",
        name: "Prescription for Terror",
        Author: "Sandra Levy Ceren",
        Year_of_publication: 1999,
        Publisher: "Andrew Scott Publishers",
        imageUrl_s: "http://images.amazon.com/images/P/0966986105.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0966986105.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0966986105.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0966986105',
        descreption:"JACK BURKE M.D. WAS BURNED OUT. The star orthopaedic surgeon had lost his special edge. He still had skills but no heart for his patients. When an R&R vacation to Belize drops him into a deadly terrorist plot to kidnap an Israeli ambassador's son, Burke is forced to remember what it means to actually give a damn."
      },
      {
        id: "087113375X",
        name: "Modern Manners: An Etiquette Book for Rude People",
        Author: "P.J. O'Rourke",
        Year_of_publication: 1990,
        Publisher: "Atlantic Monthly Press",
        imageUrl_s: "http://images.amazon.com/images/P/087113375X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/087113375X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/087113375X.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/087113375X',
        descreption:"In Modern Manners cultural guru P. J. O'Rourke provides the essential accessory for the truly contemporary man or woman-a rulebook for living in a world without rules. Traditionally, good manners were a means of becoming as bland and invisible as everyone else, and thus of avoiding calling attention to one's own awkwardness and stupidity."
      },
      {
        id: "0340767936",
        name: "Turning Thirty",
        Author: "Mike Gayle",
        Year_of_publication: 2000,
        Publisher: "Hodder &amp; Stoughton General Division",
        imageUrl_s: "http://images.amazon.com/images/P/0340767936.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0340767936.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0340767936.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0340767936',
        descreption:"Unlike most people Matt Beckford is actually looking forward to turning thirty. After struggling through most of his twenties he thinks his career, finances and love life are finally sorted. But when he splits up with his girlfriend, he realises that life has different plans for him."
      },
      {
        id: "0743403843",
        name: "Decipher",
        Author: "Stel Pavlou",
        Year_of_publication: 2002,
        Publisher: "Simon &amp; Schuster (Trade Division)",
        imageUrl_s: "http://images.amazon.com/images/P/0743403843.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0743403843.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0743403843.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0743403843',
        descreption:"The novel is about a fictional linguist, Richard Scott, and an assembled team of specialists who are in a race against time to crack a code found on ancient monuments around the world before an impending cataclysm predicted in mythology can strike."
      },
      {
        id: "0060930365",
        name: "My First Cousin Once Removed: Money, Madness, and the Family of Robert Lowell",
        Author: "Sarah Payne Stuart",
        Year_of_publication: 1999,
        Publisher: "Perennial",
        imageUrl_s: "http://images.amazon.com/images/P/0060930365.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060930365.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060930365.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0060930365',
        descreption:"at once hilarious, personal and sad--of her extraordinary Boston Brahmin family, whose most famous member is the legendary poet Robert Lowell, the author's first cousin (once removed)."
      },
      {
        id: "0060177586",
        name: "Standing Firm: A Vice-Presidential Memoir",
        Author: "Dan Quayle",
        Year_of_publication: 1994,
        Publisher: "Harpercollins",
        imageUrl_s: "http://images.amazon.com/images/P/0060177586.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060177586.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060177586.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0060177586',
        descreption:"The former vice president and conservative spokesman offers a personal account of his controversial years in the White House, from helping prosecute the war against Iraq to starting the debate over family values."
      },
      {
        id: "0071416331",
        name: "Team Bush : Leadership Lessons from the Bush White House",
        Author: "Donald F. Kettl",
        Year_of_publication: 2003,
        Publisher: "McGraw-Hill",
        imageUrl_s: "http://images.amazon.com/images/P/0071416331.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0071416331.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0071416331.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0071416331',
        descreption:"This fast-paced yet powerful book explains how the Bush model can be used by any executive to streamline management and decision processes--and establishes a new standard for results-oriented leadership in the 21st century."
      },
      {
        id: "0375509038",
        name: "The Right Man : The Surprise Presidency of George W. Bush",
        Author: "DAVID FRUM",
        Year_of_publication: 2003,
        Publisher: "Random House",
        imageUrl_s: "http://images.amazon.com/images/P/0375509038.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0375509038.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0375509038.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0375509038',
        descreption:"It is the first inside account of a historic year in the Bush White House, by the presidential speechwriter credited with the phrase axis of evil. David Frum helped make international headlines when President George W. Bush's 2002 State of the Union address linked international terrorists to Iran, Iraq, and North Korea. But that was only one moment during a crucial time in American history, when a president, an administration, and a country were transformed."
      },
      {
        id: "0553062042",
        name: "Daybreakers Louis Lamour Collection",
        Author: "Louis Lamour",
        Year_of_publication: 1981,
        Publisher: "Bantam Doubleday Dell",
        imageUrl_s: "http://images.amazon.com/images/P/0553062042.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0553062042.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0553062042.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0553062042',
        descreption:"Tyrel Sackett was born to trouble, but vowed to justice. After having to kill a man in Tennessee, he hit the trail west with his brother Orrin. Those were the years when decent men and women lived in fear of Indians, rustlers, and killers, but the Sackett brothers worked to make the West a place where people could raise their children in peace."
      },
      {
        id: "0316769487",
        name: "The Catcher in the Rye",
        Author: "J.D. Salinger",
        Year_of_publication: 1991,
        Publisher: "Little, Brown",
        imageUrl_s: "http://images.amazon.com/images/P/0316769487.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0316769487.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0316769487.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0316769487',
        descreption:"novel by J.D. Salinger published in 1951. The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school. Confused and disillusioned, Holden searches for truth and rails against the “phoniness” of the adult world."
      },
      {
        id: "8445071408",
        name: "El Senor De Los Anillos: LA Comunidad Del Anillo (Lord of the Rings (Spanish))",
        Author: "J. R. R. Tolkien",
        Year_of_publication: 2001,
        Publisher: "Minotauro",
        imageUrl_s: "http://images.amazon.com/images/P/8445071408.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/8445071408.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/8445071408.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/8445071408',
        descreption:"The Company has been dissolved and its members are going their separate ways. Frodo and Sam continue their journey alone along the Anduin River, haunted by the mysterious shadow of a strange being who also covets possession of the Ring. Meanwhile, men, elves, and dwarves prepare for the final battle against the forces of the Evil Lord."
      },
      {
        id: "8445071769",
        name: "El Senor De Los Anillos: Las DOS Torres (Lord of the Rings (Paperback))",
        Author: "J. R. R. Tolkien",
        Year_of_publication: 2001,
        Publisher: "Minotauro",
        imageUrl_s: "http://images.amazon.com/images/P/8445071769.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/8445071769.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/8445071769.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/8445071769',
        descreption:"Barcelona. 19 cm. 476 p. Encuadernación en tapa blanda de editorial ilustrada. Colección 'El Señor de los Anillos', numero coleccion(2). Tolkien, J. R. 1892-1973. Traducción de Matilde Horne y Luis Domènech. Título original: The two towers. En la portada: Minotauro. Horne, Matilde. 1914-2008. Domènech, Luis. 1922-2014. Biblioteca J. Tolkien (Booket (Editorial)). numero coleccion( 5017/2)."
      },
      {
        id: "8445071777",
        name: "El Senor De Los Anillos: El Retorno Del Rey (Tolkien, J. R. R. Lord of the Rings. 3.)",
        Author: "J. R. R. Tolkien",
        Year_of_publication: 2001,
        Publisher: "Distribooks",
        imageUrl_s: "http://images.amazon.com/images/P/8445071777.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/8445071777.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/8445071777.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/8445071777',
        descreption:"As the Shadow of Mordor grows across the land, Aragorn is revealed as the hidden heir of the ancient kings. Gandalf miraculously returns and defeats the evil wizard, Saruman. Sam leaves his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive -- in the hands of the Orcs. And all the while the armies of the Dark Lord are massing -- and the One Ring comes ever closer to the Cracks of Doom."
      },
      {
        id: "0679429220",
        name: "Midnight in the Garden of Good and Evil: A Savannah Story",
        Author: "John Berendt",
        Year_of_publication: 1994,
        Publisher: "Random House",
        imageUrl_s: "http://images.amazon.com/images/P/0679429220.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0679429220.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0679429220.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0679429220',
        descreption:"Shots rang out in Savannah's grandest mansion in the misty,early morning hours of May 2, 1981.  Was it murder or self-defense?  For nearly a decade, the shooting and its aftermath reverberated throughout this hauntingly beautiful city of moss-hung oaks and shaded squares."
      },
      {
        id: "0671867156",
        name: "Pretend You Don't See Her",
        Author: "Mary Higgins Clark",
        Year_of_publication: 1998,
        Publisher: "Pocket",
        imageUrl_s: "http://images.amazon.com/images/P/0671867156.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0671867156.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0671867156.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0671867156',
        descreption:"What happens when a young woman is accidentally caught up in a dangerous murder investigation, having merely been in the wrong place at the wrong time? Lacey Farrell, a rising star on the Manhattan real estate scene, is witness to a murder - and to the final words of the victim."
      },
      {
        id: "0312252617",
        name: "Fast Women",
        Author: "Jennifer Crusie",
        Year_of_publication: 2001,
        Publisher: "St. Martin's Press",
        imageUrl_s: "http://images.amazon.com/images/P/0312252617.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0312252617.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0312252617.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0312252617',
        descreption:"Nell Dysart's in trouble. Weighed down by an inexplicable divorce and a loss of appetite for everything, Nell is sleepwalking through life until her best friend finagles a job for her with a shabby little detective agency that has lots of potential and a boss who looks easy to manage."
      },
      {
        id: "0312261594",
        name: "Female Intelligence",
        Author: "Jane Heller",
        Year_of_publication: 2001,
        Publisher: "St. Martin's Press",
        imageUrl_s: "http://images.amazon.com/images/P/0312261594.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0312261594.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0312261594.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0312261594',
        descreption:"A contemporary comedy of manners, Female Intelligence is a social satire about the way men and women communicate - or don't. Dr. Lynn Wyman has a wildly successful practice in sensitivity training, instructing men how to become fluent in the language of Womenspeak so they can relate better to the women in their lives."
      },
      {
        id: "0316748641",
        name: "Pasquale's Nose: Idle Days in an Italian Town",
        Author: "Michael Rips",
        Year_of_publication: 2002,
        Publisher: "Back Bay Books",
        imageUrl_s: "http://images.amazon.com/images/P/0316748641.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0316748641.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg",
        linkUrl:'/sneakers/0316748641',
        descreption:"Everywhere hailed for its quirkiness, its hilarity, its charm, Pasquale's Nose tells the story of a New York City lawyer who runs away to a small Etruscan village with his wife and new baby, and discovers a community of true eccentrics."
      }


    ]
  },
  jackets:{
    id: 3,
    title: 'Jackets',
    routeName: 'jackets',
    items: [
      {
        id: "0679865691",
        name: "Haveli (Laurel Leaf Books)",
        Author: "SUZANNE FISHER STAPLES",
        Year_of_publication: 1995,
        Publisher: "Laurel Leaf",
        imageUrl_s: "http://images.amazon.com/images/P/0679865691.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0679865691.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0679865691.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0679865691',
        descreption:"Haveli continues the story of Shabanu, who is the fourth and youngest wife of a rich and powerful man. She is looked down upon by the other wives, because she is from a desert nomadic tribe, and is considered beneath them. However, with her intelligence and her free spirit, she manages to survive and thrive in this life that was forced upon her."
      },
      {
        id: "2070423204",
        name: "Lieux dits",
        Author: "Michel Tournier",
        Year_of_publication: 2002,
        Publisher: "Gallimard",
        imageUrl_s: "http://images.amazon.com/images/P/2070423204.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/2070423204.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/2070423204.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/2070423204',
        descreption:"Atlas and History of Site Names of Burgundy Vineyards by Marie-Hélène Landrieu-Lussigny & Sylvian Pitiot. Text is in English. A 2000-year History of the Greatest Vineyards of Burgundy, a patchwork of numerous parcels named Climats and Lieux-dits have given this famous area its originality! A 200-year History of hard working men who have taken advantage of the incredible diversity of geographic situations."
      },
      {
        id: "0345260317",
        name: "The Dragons of Eden: Speculations on the Evolution of Human Intelligence",
        Author: "Carl Sagan",
        Year_of_publication: 1978,
        Publisher: "Ballantine Books",
        imageUrl_s: "http://images.amazon.com/images/P/0345260317.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0345260317.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0345260317.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0345260317',
        descreption:"It is a 1977 book by Carl Sagan, in which the author combines the fields of anthropology, evolutionary biology, psychology, and computer science to give a perspective on how human intelligence may have evolved."
      },
      {
        id: "0394743741",
        name: "The yawning heights",
        Author: "Aleksandr Zinoviev",
        Year_of_publication: 1980,
        Publisher: "Random House",
        imageUrl_s: "http://images.amazon.com/images/P/0394743741.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0394743741.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0394743741.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0394743741',
        descreption:"Yawning Heights is the first published novel by Soviet philosopher Alexander Zinoviev. Zinoviev expressed skepticism and frustration toward writings that attempted to expose and reveal the evils of Soviet communism."
      },
      {
        id: "042511774X",
        name: "Breathing Lessons",
        Author: "Anne Tyler",
        Year_of_publication: 1994,
        Publisher: "Berkley Publishing Group",
        imageUrl_s: "http://images.amazon.com/images/P/042511774X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/042511774X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/042511774X.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/042511774X',
        descreption:"The story describes the joys and pains of the ordinary marriage of Ira and Maggie Moran as they travel from Baltimore to attend a funeral and back home again in one day. It also examines Maggie's attempts to reconcile her son and daughter-in-law."
      },
      {
        id: "0804106304",
        name: "The Joy Luck Club",
        Author: "Amy Tan",
        Year_of_publication: 1994,
        Publisher: "Prentice Hall (K-12)",
        imageUrl_s: "http://images.amazon.com/images/P/0804106304.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0804106304.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0804106304.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0804106304',
        descreption:"It focuses on four Chinese American immigrant families in San Francisco who start a club known as The Joy Luck Club, playing the Chinese game of mahjong for money while feasting on a variety of foods."
      },
      {
        id: "1853262404",
        name: "Heart of Darkness (Wordsworth Collection)",
        Author: "Joseph Conrad",
        Year_of_publication: 1998,
        Publisher: "NTC/Contemporary Publishing Company",
        imageUrl_s: "http://images.amazon.com/images/P/1853262404.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1853262404.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1853262404.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/1853262404',
        descreption:"One measure, perhaps, of a book's worth, is its intergenerational pliancy: do new readers acquire it and interpret it afresh down through the ages? The meditationsof Marcus Aurelius, translated and introduced by Gregory Hays, by that standard, is very worthwhile, indeed. Hays suggests that its most recent incarnation - as a self-help book - is not only valid, but may be close to the author's intent. "
      },
      {
        id: "0312970242",
        name: "The Angel Is Near",
        Author: "Deepak Chopra",
        Year_of_publication: 2000,
        Publisher: "St. Martin's Press",
        imageUrl_s: "http://images.amazon.com/images/P/0312970242.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0312970242.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0312970242.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0312970242',
        descreption:"Two American soldiers are carefully checking a church in Kosovo for mines when there is an explosion. In fact, the soldiers are convinced they saw a messenger from God. Soon after, a doctor rushes to help a neighbor who is apparently having a heart attack."
      },
      {
        id: "1853260053",
        name: "Tess of the D'Urbervilles (Wordsworth Classics)",
        Author: "Thomas Hardy",
        Year_of_publication: 1997,
        Publisher: "NTC/Contemporary Publishing Company",
        imageUrl_s: "http://images.amazon.com/images/P/1853260053.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1853260053.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1853260053.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/1853260053',
        descreption:"A novel of hypocrisy and double standards. It tells of Tess Durbeyfield, the daughter of a poor and dissipated villager, who learns that she may be descended from the ancient family of d'Urbeville. In her search for respectability her fortunes fluctuate wildly, and the story assumes the proportions of a Greek tragedy."
      },
      {
        id: "1414035004",
        name: "The Adventures of Drew and Ellie: The Magical Dress",
        Author: "Charles Noland",
        Year_of_publication: 2003,
        Publisher: "1stBooks Library",
        imageUrl_s: "http://images.amazon.com/images/P/1414035004.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1414035004.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1414035004.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/1414035004',
        descreption:"In Charles Noland's book, The Adventures of Drew and Ellie: The Magical Dress, children can join 7-year-old Drew and his 4-year-old sister Ellie as they embark on the greatest adventure of their lives. This book series will teach children important life lessons about cooperation, creativity and caring for each other."
      },
      {
        id: "0060938412",
        name: "The Accidental Virgin",
        Author: "Valerie Frankel",
        Year_of_publication: 2003,
        Publisher: "Avon Trade",
        imageUrl_s: "http://images.amazon.com/images/P/0060938412.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060938412.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060938412.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0060938412',
        descreption:"You were so promising at the beginning: Sexy, smart, personable and funny. Great on dates and really great afterward-if you know what I mean. But this is a sad state of affairs; or, in your case, non-affairs! It's been nearly an entire year and you had had your way with even ONE eligible male."
      },
      {
        id: "0140067477",
        name: "The Tao of Pooh",
        Author: "Benjamin Hoff",
        Year_of_publication: 1983,
        Publisher: "Penguin Books",
        imageUrl_s: "http://images.amazon.com/images/P/0140067477.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0140067477.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0140067477.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0140067477',
        descreption:"The Tao of Pooh is a book written by Benjamin Hoff. The book is intended as an introduction to the Eastern belief system of Taoism for Westerners. It allegorically employs the fictional characters of A. A. Milne's Winnie-the-Pooh stories to explain the basic principles of philosophical Taoism."
      },
      {
        id: "0345465083",
        name: "Seabiscuit",
        Author: "LAURA HILLENBRAND",
        Year_of_publication: 2003,
        Publisher: "Ballantine Books",
        imageUrl_s: "http://images.amazon.com/images/P/0345465083.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0345465083.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0345465083.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0345465083',
        descreption:"The book tells the story of Seabiscuit, possibly the most famous American racehorse of all time, with special emphasis on the human beings who discovered him, trained him, and risked both their lives and their money on him. Seabiscuit captured the nation's imagination at the height of the Great Depression."
      },
      {
        id: "0451625889",
        name: "The Prince",
        Author: "Niccolo Machiavelli",
        Year_of_publication: 1952,
        Publisher: "Signet Book",
        imageUrl_s: "http://images.amazon.com/images/P/0451625889.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0451625889.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0451625889.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0451625889',
        descreption:"The Prince is a how-to for aspiring rulers. The book disregards republics and hereditary principalities to focus on mixed and new principalities. When ruling a mixed principality, Machiavelli highlights the importance of befriending the weak and destroying anyone who may become powerful enough to revolt."
      },
      {
        id: "1558531025",
        name: "Life's Little Instruction Book (Life's Little Instruction Books (Paperback))",
        Author: "H. Jackson Brown",
        Year_of_publication: 1991,
        Publisher: "Thomas Nelson",
        imageUrl_s: "http://images.amazon.com/images/P/1558531025.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1558531025.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1558531025.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/1558531025',
        descreption:"Though originally written as a gift from a father to a son, its simple message has been enjoyed by men and women of all ages. Most of us already know how to live a successful and purposeful life,says the author. We know we should be understanding and thoughtful, responsible, courageous, and appreciative. It's just that we sometimes need reminding."
      },
      {
        id: "0441783589",
        name: "Starship Troopers",
        Author: "Robert A. Heinlein",
        Year_of_publication: 1987,
        Publisher: "Ace Books",
        imageUrl_s: "http://images.amazon.com/images/P/0441783589.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0441783589.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0441783589.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0441783589',
        descreption:"It tells the story of an interplanetary war between Earth and colonies of large insect-like aliens in the twenty-third century. It focuses on the experiences of Johnny Rico (Casper Van Dien), one of three friends who sign up to the military one year before Earth declares war on the Arachnids."
      },
      {
        id: "0394895894",
        name: "The Ruby in the Smoke (Sally Lockhart Trilogy, Book 1)",
        Author: "PHILIP PULLMAN",
        Year_of_publication: 1988,
        Publisher: "Laurel Leaf",
        imageUrl_s: "http://images.amazon.com/images/P/0394895894.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0394895894.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0394895894.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/0394895894',
        descreption:"The first book in Philip Pullman's classic SALLY LOCKHART quartet in a beautiful new edition to celebrate the 30 year anniversary. Soon after Sally Lockhart's father drowns at sea, she receives an anonymous letter. The dire warning it contains makes a man die of fear at her feet."
      },
      {
        id: "1569871213",
        name: "Black Beauty (Illustrated Classics)",
        Author: "Anna Sewell",
        Year_of_publication: 1995,
        Publisher: "Landoll",
        imageUrl_s: "http://images.amazon.com/images/P/1569871213.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1569871213.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1569871213.01.LZZZZZZZ.jpg",
        linkUrl:'/jackets/1569871213',
        descreption:"Beautifully written, Black Beauty reveals what life was like for a horse during the Victorian era. Read all about his life as a young colt, his adventures growing up, and learn about life as a cab-horse on bustling London streets."
      },
    ]
  },
  womens:{
    id: 4,
    title: 'Womens',
    routeName: 'womens',
    items: [
      {
        id: "0060168013",
        name: "Pigs in Heaven",
        Author: "Barbara Kingsolver",
        Year_of_publication: 1993,
        Publisher: "Harpercollins",
        imageUrl_s: "http://images.amazon.com/images/P/0060168013.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060168013.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060168013.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0060168013',
        descreption:"Pigs in Heaven is a 1993 novel by Barbara Kingsolver; it is the sequel to her first novel, The Bean Trees. It continues the story of Taylor Greer and Turtle, her adopted Cherokee daughter."
      },
      {
        id: "038078243X",
        name: "Miss Zukas and the Raven's Dance",
        Author: "Jo Dereske",
        Year_of_publication: 1996,
        Publisher: "Avon",
        imageUrl_s: "http://images.amazon.com/images/P/038078243X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/038078243X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/038078243X.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/038078243X',
        descreption:"A most unusual death has landed Helma Zukas right in the middle of another murder scene. Stanley Plummer had been cataloguing a collection of Native American books for Bellehaven's new Cultural Center when his body was found in the Center's ladies room - stabbed through the heart, and clutching a Barbie doll."
      },
      {
        id: "055321215X",
        name: "Pride and Prejudice",
        Author: "Jane Austen",
        Year_of_publication: 1983,
        Publisher: "Bantam",
        imageUrl_s: "http://images.amazon.com/images/P/055321215X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/055321215X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/055321215X.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/055321215X',
        descreption:"Pride and Prejudice follows the turbulent relationship between Elizabeth Bennet, the daughter of a country gentleman, and Fitzwilliam Darcy, a rich aristocratic landowner. They must overcome the titular sins of pride and prejudice in order to fall in love and marry."
      },
      {
        id: "067176537X",
        name: "The Therapeutic Touch: How to Use Your Hands to Help or to Heal",
        Author: "Dolores Krieger",
        Year_of_publication: 1979,
        Publisher: "Fireside",
        imageUrl_s: "http://images.amazon.com/images/P/067176537X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/067176537X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/067176537X.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/067176537X',
        descreption:"Whether it be to relieve a headache, calm a muscle spasm, soothe a crying baby, or alleviate your own abdominal cramps. The Therapeutic Touch shows you how you can use your hands to help or to heal someone who is sick. By explaining what happens during the four different stages of therapeutic touching."
      },
      {
        id: "0061099686",
        name: "Downtown",
        Author: "Anne Rivers Siddons",
        Year_of_publication: 1995,
        Publisher: "HarperTorch",
        imageUrl_s: "http://images.amazon.com/images/P/0061099686.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0061099686.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0061099686.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0061099686',
        descreption:"Anne Rivers Siddons, whose best-selling novels such as “Peachtree Road,” “Outer Banks” and “Low Country” often portrayed the lives of women coming to terms with the social mores of the South, died Sept. 11 at her home in Charleston, S.C. She was 83."
      },
      {
        id: "0553582909",
        name: "Icebound",
        Author: "Dean R. Koontz",
        Year_of_publication: 2000,
        Publisher: "Bantam Books",
        imageUrl_s: "http://images.amazon.com/images/P/0553582909.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0553582909.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0553582909.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0553582909',
        descreption:"The plot concerns a group of international scientists working for the project of towing an iceberg to be used as relief for droughts. It is headed up by the husband and wife team of Rita and Harold (Harry) Carpenter. Rita secretly suffers from the fear of cold, ice and snow."
      },
      {
        id: "0671888587",
        name: "I'll Be Seeing You",
        Author: "Mary Higgins Clark",
        Year_of_publication: 1994,
        Publisher: "Pocket",
        imageUrl_s: "http://images.amazon.com/images/P/0671888587.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0671888587.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0671888587.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0671888587',
        descreption:"The mix of emotions on everyone's part could make every day feel like walking through a minefield. Then came redemption. I'll Be Seeing You charts the passage from the anguish of loss to the understanding that even in the most fractious times, love can heal, transform, and lead to graceful—and grateful—acceptance."
      },
      {
        id: "0553582747",
        name: "From the Corner of His Eye",
        Author: "Dean Koontz",
        Year_of_publication: 2001,
        Publisher: "Bantam Books",
        imageUrl_s: "http://images.amazon.com/images/P/0553582747.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0553582747.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0553582747.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0553582747',
        descreption:"From the Corner of His Eye is a novel by best-selling author Dean Koontz, released in 2000. It is the story of a boy named Barty Lampion, a ruthless killer named Junior Cain, and a girl named Angel, born as the result of a rape."
      },
      {
        id: "0425182908",
        name: "Isle of Dogs",
        Author: "Patricia Cornwell",
        Year_of_publication: 2002,
        Publisher: "Berkley Publishing Group",
        imageUrl_s: "http://images.amazon.com/images/P/0425182908.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0425182908.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0425182908.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0425182908',
        descreption:"Isle of Dogs tells the story of Atari Kobayashi, 12-year-old ward to corrupt Mayor Kobayashi. When, by Executive Decree, all the canine pets of Megasaki City are exiled to a vast garbage-dump called Trash Island, Atari sets off alone in a miniature Junior-Turbo Prop and flies across the river in search of his bodyguard-dog, Spots."
      },
      {
        id: "042518630X",
        name: "Purity in Death",
        Author: "J.D. Robb",
        Year_of_publication: 2002,
        Publisher: "Berkley Publishing Group",
        imageUrl_s: "http://images.amazon.com/images/P/042518630X.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/042518630X.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/042518630X.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/042518630X',
        descreption:"Lt. Eve Dallas and her assistant, Delia Peabody, are called in by Officer Troy Trueheart after he has shot and killed a suspect named Louie Cogburn. The man, a known but unconvicted, normally low-profile dealer in illegals (illegal drugs) to children, had suddenly turned homicidally insane and killed a neighbor in his apartment building; he was attacking the neighbor's wife when Trueheart enters the scene."
      },
      {
        id: "0440223571",
        name: "This Year It Will Be Different: And Other Stories",
        Author: "Maeve Binchy",
        Year_of_publication: 1997,
        Publisher: "Dell",
        imageUrl_s: "http://images.amazon.com/images/P/0440223571.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0440223571.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0440223571.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0440223571',
        descreption:"The title story This Year It Will Be Different also delves into the emotions of a person at mid-life--a woman with a complacent husband and grown children who are entering a season that can forever alter her life, and theirs."
      },
      {
        id: "0812523873",
        name: "Proxies",
        Author: "Laura J. Mixon",
        Year_of_publication: 1999,
        Publisher: "Tor Books",
        imageUrl_s: "http://images.amazon.com/images/P/0812523873.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0812523873.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0812523873.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0812523873',
        descreption:"Proxy is a 2013 sci-fi, dystopian young adult novel by Alex London. The novel, which was released on June 18, 2013, features a gay adolescent as its action-hero protagonist. A sequel to the novel has been released in 2014, Guardian."
      },
      {
        id: "0842342702",
        name: "Left Behind: A Novel of the Earth's Last Days (Left Behind #1)",
        Author: "Tim Lahaye",
        Year_of_publication: 2000,
        Publisher: "Tyndale House Publishers",
        imageUrl_s: "http://images.amazon.com/images/P/0842342702.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0842342702.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0842342702.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0842342702',
        descreption:"An airborne Boeing 747 is headed to London when, without any warning, passengers mysteriously disappear from their seats. Terror and chaos slowly spread not only through the plane, but also worldwide as unusual events continue to unfold."
      },
      {
        id: "0440225701",
        name: "The Street Lawyer",
        Author: "JOHN GRISHAM",
        Year_of_publication: 1999,
        Publisher: "Dell",
        imageUrl_s: "http://images.amazon.com/images/P/0440225701.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0440225701.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0440225701.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0440225701',
        descreption:"A homeless man, identifying himself only as Mister, enters the offices of the powerful Washington D.C. law firm Drake & Sweeney and takes many of the lawyers hostage while angrily demanding information about some kind of eviction that took place."
      },
      {
        id: "0060914068",
        name: "Love, Medicine and Miracles",
        Author: "M.D. Bernie S. Siegel",
        Year_of_publication: 1988,
        Publisher: "HarperCollins Publishers",
        imageUrl_s: "http://images.amazon.com/images/P/0060914068.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0060914068.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0060914068.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0060914068',
        descreption:"Unconditional love is the most powerful stimulant of the immune system. The truth is: love heals. Miracles happen to exceptional patients every day—patients who have the courage to love, those who have the courage to work with their doctors to participate in and influence their own recovery."
      },
      {
        id: "0156047624",
        name: "All the King's Men",
        Author: "Robert Penn Warren",
        Year_of_publication: 1982,
        Publisher: "Harvest Books",
        imageUrl_s: "http://images.amazon.com/images/P/0156047624.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0156047624.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0156047624.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0156047624',
        descreption:"It is one of American literature's definitive political novels, as well as a profound study of human fallibility in politics. Set in the 1930s, it describes the dramatic rise to power, as state governor, of Willie Stark, a one-time radical attorney."
      },
      {
        id: "0245542957",
        name: "Pacific Northwest",
        Author: "Hans Johannes Hoefer",
        Year_of_publication: 1985,
        Publisher: "Chambers Harrap Publishers Ltd",
        imageUrl_s: "http://images.amazon.com/images/P/0245542957.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0245542957.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0245542957.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0245542957',
        descreption:"A teenager yearns to escape her mundane life and sleepy hometown in Alaska for the excitement that surely awaits her in a bigger city or a college town in the lower forty-eight states in this debut young-adult novel by Pacific Northwest author Meagan Macvie."
      },
      {
        id: "0380715899",
        name: "A Soldier of the Great War",
        Author: "Mark Helprin",
        Year_of_publication: 1992,
        Publisher: "Avon Books",
        imageUrl_s: "http://images.amazon.com/images/P/0380715899.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0380715899.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0380715899.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0380715899',
        descreption:"The book focuses on an aged World War I veteran who recounts his life and adventures while traveling with a young man he meets after the two of them are thrown off a bus, the former leaving after the latter is refused entry, as the older man marches toward a visit with his granddaughter, neither knowing the outcome."
      },
      {
        id: "0553280333",
        name: "Getting Well Again",
        Author: "O. Carol Simonton Md",
        Year_of_publication: 1992,
        Publisher: "Bantam",
        imageUrl_s: "http://images.amazon.com/images/P/0553280333.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0553280333.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0553280333.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0553280333',
        descreption:"In this revolutionary book the Simontons profile the typical cancer personality how an individual's reactions to stress and other emotional factors can contribute to the onset and progress of cancer — and how positive expectations, self-awareness, and self-care can contribute to survival."
      },
      {
        id: "0961769947",
        name: "Northwest Wines and Wineries",
        Author: "Chuck Hill",
        Year_of_publication: 1993,
        Publisher: "Speed Graphics",
        imageUrl_s: "http://images.amazon.com/images/P/0961769947.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0961769947.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0961769947.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0961769947',
        descreption:"Superbly balanced pinot noirs; crisp rieslings; rich, heady syrahs: these are only a fraction of the expertly crafted wines being produced in the Pacific Northwest's diverse and distinctive wine countries. Second only to California in production, the Pacific Northwest is the largest wine region in North America, home to more than 1,000 wineries."
      },
      {
        id: "0964778319",
        name: "An Atmosphere of Eternity: Stories of India",
        Author: "David Iglehart",
        Year_of_publication: 2002,
        Publisher: "Sunflower Press",
        imageUrl_s: "http://images.amazon.com/images/P/0964778319.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0964778319.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0964778319.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0964778319',
        descreption:"A collection of short stories set in India, dealing with the unpredictable effects of contact between those who live there and visiting westerners. The stories give us a rare opportunity to see life through the eyes of Indians and Americans living, working, loving, and dying in a country steeped in the spiritual--in an atmosphere of eternity."
      },
      {
        id: "0671623249",
        name: "LONESOME DOVE",
        Author: "Larry McMurtry",
        Year_of_publication: 1986,
        Publisher: "Pocket",
        imageUrl_s: "http://images.amazon.com/images/P/0671623249.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0671623249.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0671623249.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0671623249',
        descreption:"The story focuses on the relationship among several retired Texas Rangers and their adventures driving a cattle herd from Texas to Montana. Set in the closing years of the Old West, the novel explores themes of old age, death, unrequited love, and friendship."
      },
      {
        id: "0679810307",
        name: "Shabanu: Daughter of the Wind (Border Trilogy)",
        Author: "SUZANNE FISHER STAPLES",
        Year_of_publication: 1991,
        Publisher: "Laurel Leaf",
        imageUrl_s: "http://images.amazon.com/images/P/0679810307.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0679810307.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0679810307.01.LZZZZZZZ.jpg",
        linkUrl:'/womens/0679810307',
        descreption:"Staples is so steeped in her story and its Pakistani setting that the use of a first-person voice for a desert child rings authentic--the voice is clear, consistent, and convincing. Shabanu and her sister are to marry brothers as soon as they all come of age. But she will eventually lose her betrothed and be promised to a wealthy landowner to settle a feud."
      },

    ]
  },
  mens:{
    id: 5,
    title: 'Mens',
    routeName: 'mens',
    items: [
      {
        id: "1881320189",
        name: "Goodbye to the Buttermilk Sky",
        Author: "Julia Oliver",
        Year_of_publication: 1994,
        Publisher: "River City Pub",
        imageUrl_s: "http://images.amazon.com/images/P/1881320189.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1881320189.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1881320189.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/1881320189',
        descreption:"A beautifully narrated novel of time and place, Goodbye to the Buttermilk Sky re-creates a southern summer when the depression and the boll weevil turned hopes to dust. With the extraordinary talent to make the reader see the Ball canning jars on the kitchen table, hear the clicks on the party line, and feel the bittersweet moments of 20-year-old Callie Tatum's first experiences with adult desire."
      },
      {
        id: "0440234743",
        name: "The Testament",
        Author: "John Grisham",
        Year_of_publication: 1999,
        Publisher: "Dell",
        imageUrl_s: "http://images.amazon.com/images/P/0440234743.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0440234743.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0440234743.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0440234743',
        descreption:"In a story that mixes legal suspense with a remarkable adventure, their lives are forever altered by the startling secret of The Testament. Troy Phelan is a self-made billionaire, one of the richest men in the United States. He is also eccentric, reclusive, confined to a wheelchair, and looking for a way to die."
      },
      {
        id: "0452264464",
        name: "Beloved (Plume Contemporary Fiction)",
        Author: "Toni Morrison",
        Year_of_publication: 1994,
        Publisher: "Plume",
        imageUrl_s: "http://images.amazon.com/images/P/0452264464.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0452264464.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0452264464',
        descreption:"In the troubled years following the Civil War, the spirit of a murdered child haunts the Ohio home of a former slave. This angry, destructive ghost breaks mirrors, leaves its fingerprints in cake icing, and generally makes life difficult for Sethe and her family; nevertheless, the woman finds the haunting oddly comforting for the spirit is that of her own dead baby, never named, thought of only as Beloved."
      },
      {
        id: "0609804618",
        name: "Our Dumb Century: The Onion Presents 100 Years of Headlines from America's Finest News Source",
        Author: "The Onion",
        Year_of_publication: 1999,
        Publisher: "Three Rivers Press",
        imageUrl_s: "http://images.amazon.com/images/P/0609804618.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0609804618.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0609804618.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0609804618',
        descreption:"The Onion has quickly become the world's most popular humor publication, misinforming half a million readers a week with one-of-a-kind social satire both in print (on newsstands nationwide) and online from its remote office in Madison, Wisconsin."
      },
      {
        id: "1841721522",
        name: "New Vegetarian: Bold and Beautiful Recipes for Every Occasion",
        Author: "Celia Brooks Brown",
        Year_of_publication: 2001,
        Publisher: "Ryland Peters &amp; Small Ltd",
        imageUrl_s: "http://images.amazon.com/images/P/1841721522.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1841721522.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1841721522.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/1841721522',
        descreption:"Here, innovative young chef Celia Brooks Brown gives meat-free cooking a new lease of life. From quick weekday lunches, snacks, and dinners to sophisticated dinner parties, you'll find a feast of delicious recipes for every occasion. Inspired by the great vegetarian cuisines of Asia and the Middle East, as well as the Mediterranean, New Vegetarian is bold, bright, and beautiful."
      },
      {
        id: "1879384493",
        name: "If I'd Known Then What I Know Now: Why Not Learn from the Mistakes of Others? : You Can't Afford to Make Them All Yourself",
        Author: "J. R. Parrish",
        Year_of_publication: 2003,
        Publisher: "Cypress House",
        imageUrl_s: "http://images.amazon.com/images/P/1879384493.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/1879384493.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/1879384493.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/1879384493',
        descreption:"If I'd Known Then What I Know Now is an inspiring, Pay It Forward-type manifesto for achieving success and happiness from childhood to retirement. Equally suitable for anyone from eight to eighty, it is actually a life guide or map that will help the reader traverse the roads of life, showing how to avoid the mindfields and grab the gold ring by making the best choices when facing life's most important decisions."
      },
      {
        id: "0061076031",
        name: "Mary-Kate &amp; Ashley Switching Goals (Mary-Kate and Ashley Starring in)",
        Author: "Mary-Kate &amp; Ashley Olsen",
        Year_of_publication: 2000,
        Publisher: "HarperEntertainment",
        imageUrl_s: "http://images.amazon.com/images/P/0061076031.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0061076031.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0061076031.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0061076031',
        descreption:"Emma Stanton is a boy magnet. Her twin sister, Sam, is an all-star athlete. So what do they do when Emma wants to get closer to her sports-crazed dad, and Sam wants to catch the attention of the cutest boy in school? Simple. Switch places!"
      },
      {
        id: "0439095026",
        name: "Tell Me This Isn't Happening",
        Author: "Robynn Clairday",
        Year_of_publication: 1999,
        Publisher: "Scholastic",
        imageUrl_s: "http://images.amazon.com/images/P/0439095026.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0439095026.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0439095026.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0439095026',
        descreption:"Robynn Clairday interviewed kids throughout America to collect these real tales of awkward situations. From hilarious to poignant to painful, these stories are accompanied by advice about dealing with embarrassment and finding grace under pressure."
      },
      {
        id: "0689821166",
        name: "Flood : Mississippi 1927",
        Author: "Kathleen Duey",
        Year_of_publication: 1998,
        Publisher: "Aladdin",
        imageUrl_s: "http://images.amazon.com/images/P/0689821166.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0689821166.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0689821166.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0689821166',
        descreption:"The Great Mississippi Flood of 1927 was the most destructive river flood in the history of the United States, with 27,000 square miles (70,000 km2) inundated in depths of up to 30 feet (9 m). The uninflated cost of the damage has been estimated to be between 246 million and 1 billion dollars."
      },
      {
        id: "0971880107",
        name: "Wild Animus",
        Author: "Rich Shapero",
        Year_of_publication: 2004,
        Publisher: "Too Far",
        imageUrl_s: "http://images.amazon.com/images/P/0971880107.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0971880107.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0971880107.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0971880107',
        descreption:"Wild Animus was published in 2004. From the author's website: “Wild Animus tracks the reckless quest of Ransom Altman, a young Berkeley graduate who—roused by his literary heroes and love for his girlfriend, Lindy—resolves to live in a new world of 'inexhaustible desire."
      },
      {
        id: "0345402871",
        name: "Airframe",
        Author: "Michael Crichton",
        Year_of_publication: 1997,
        Publisher: "Ballantine Books",
        imageUrl_s: "http://images.amazon.com/images/P/0345402871.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0345402871.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0345402871.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0345402871',
        descreption:"The plot follows Casey Singleton, a quality assurance vice president at the fictional aerospace manufacturer Norton Aircraft, as she investigates an in-flight accident aboard a Norton-manufactured airliner that leaves three passengers dead and 56 injured."
      },
      {
        id: "0345417623",
        name: "Timeline",
        Author: "MICHAEL CRICHTON",
        Year_of_publication: 2000,
        Publisher: "Ballantine Books",
        imageUrl_s: "http://images.amazon.com/images/P/0345417623.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0345417623.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0345417623.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0345417623',
        descreption:"Timeline is a science fiction novel by American writer Michael Crichton, his twelfth under his own name and twenty-second overall, published in November 1999. It tells the story of a group of history students who travel to 14th-century France to rescue their professor."
      },
      {
        id: "0684823802",
        name: "OUT OF THE SILENT PLANET",
        Author: "C.S. Lewis",
        Year_of_publication: 1996,
        Publisher: "Scribner",
        imageUrl_s: "http://images.amazon.com/images/P/0684823802.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0684823802.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0684823802.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0684823802',
        descreption:"the first book in the trilogy, tells the tale of a man kidnapped, taken aboard a spaceship, and transported to Malacandra or, as we know it, Mars. Dr. As he explores Malacandra and meets the aliens who call it home, he begins to understand them, and himself, in an entirely new way."
      },
      {
        id: "0375759778",
        name: "Prague : A Novel",
        Author: "ARTHUR PHILLIPS",
        Year_of_publication: 2003,
        Publisher: "Random House Trade Paperbacks",
        imageUrl_s: "http://images.amazon.com/images/P/0375759778.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0375759778.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0375759778.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0375759778',
        descreption:"Prague is a historical novel by Arthur Phillips about a group of North American expatriates in Budapest, Hungary. It is set in about 1990, at the end of the Cold War. Prague is the author's debut novel, first published by Random House in 2002."
      },
      {
        id: "0425163091",
        name: "Chocolate Jesus",
        Author: "Stephan Jaramillo",
        Year_of_publication: 1998,
        Publisher: "Berkley Publishing Group",
        imageUrl_s: "http://images.amazon.com/images/P/0425163091.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0425163091.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0425163091.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0425163091',
        descreption:"It is the funny and skeptical, yet genuine exploration of the Christian history they don't teach in Sunday school. It finds humor, irony, and occasional insight amid the inconsistencies, absurdities, hypocrisies, and flat out weirdness that too often passes for eternal truth."
      },
      {
        id: "3404921038",
        name: "Wie Barney es sieht.",
        Author: "Mordecai Richler",
        Year_of_publication: 2002,
        Publisher: "L�?¼bbe",
        imageUrl_s: "http://images.amazon.com/images/P/3404921038.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/3404921038.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/3404921038.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/3404921038',
        descreption:"Lübbe, 2002. Ausreichend/Acceptable: Exemplar mit vollständigem Text und sämtlichen Abbildungen oder Karten. Schmutztitel oder Vorsatz können fehlen. Einband bzw. Schutzumschlag weisen unter Umständen starke Gebrauchsspuren auf. / Describes a book or dust jacket that has the complete text pages (including those with maps or plates) but may lack endpapers, half-title, etc. (which must be noted)."
      },
      {
        id: "3442353866",
        name: "Der Fluch der Kaiserin. Ein Richter- Di- Roman.",
        Author: "Eleanor Cooney",
        Year_of_publication: 2001,
        Publisher: "Goldmann",
        imageUrl_s: "http://images.amazon.com/images/P/3442353866.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/3442353866.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/3442353866.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/3442353866',
        descreption:"Blanvalet, 2001. Gut/Very good: Buch bzw. Schutzumschlag mit wenigen Gebrauchsspuren an Einband, Schutzumschlag oder Seiten. / Describes a book or dust jacket that does show some signs of wear on either the binding, dust jacket or pages."
      },
      {
        id: "3442410665",
        name: "Sturmzeit. Roman.",
        Author: "Charlotte Link",
        Year_of_publication: 1991,
        Publisher: "Goldmann",
        imageUrl_s: "http://images.amazon.com/images/P/3442410665.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/3442410665.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/3442410665.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/3442410665',
        descreption:"It is fermenting in Europe, but the Degnelly family estate in East Prussia is still optimistic about the future. The 18-year-old daughter Felicia in particular dreams of an exciting, happy life. A dream that has to prove itself in difficult times, because the next few years will bring the end of her familiar world for Felicia too. Nevertheless, she loves life, risk and above all two very different men."
      },
      {
        id: "3442446937",
        name: "Tage der Unschuld.",
        Author: "Richard North Patterson",
        Year_of_publication: 2000,
        Publisher: "Goldmann",
        imageUrl_s: "http://images.amazon.com/images/P/3442446937.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/3442446937.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/3442446937.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/3442446937',
        descreption:"Book or dust jacket in average condition with traces of use, but complete pages. / Describes the average WORN book or dust jacket that has all the pages present."
      },
      {
        id: "0375406328",
        name: "Lying Awake",
        Author: "Mark Salzman",
        Year_of_publication: 2000,
        Publisher: "Alfred A. Knopf",
        imageUrl_s: "http://images.amazon.com/images/P/0375406328.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0375406328.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0375406328.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0375406328',
        descreption:"Mysticism meets modern medicine in this intriguing r cit of a nun's dark night of the soul. It's 1997, and Sister John of the Cross, a Carmelite nun in a monastery just outside Los Angeles, seeks treatment for epilepsy, although the remedy threatens to diminish her formidable spiritual powers."
      },
      {
        id: "0446310786",
        name: "To Kill a Mockingbird",
        Author: "Harper Lee",
        Year_of_publication: 1988,
        Publisher: "Little Brown &amp; Company",
        imageUrl_s: "http://images.amazon.com/images/P/0446310786.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0446310786.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0446310786.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0446310786',
        descreption:"Set in the small Southern town of Maycomb, Alabama, during the Depression, To Kill a Mockingbird follows three years in the life of 8-year-old Scout Finch, her brother, Jem, and their father, Atticus--three years punctuated by the arrest and eventual trial of a young black man accused of raping a white woman."
      },
      {
        id: "0449005615",
        name: "Seabiscuit: An American Legend",
        Author: "LAURA HILLENBRAND",
        Year_of_publication: 2002,
        Publisher: "Ballantine Books",
        imageUrl_s: "http://images.amazon.com/images/P/0449005615.01.THUMBZZZ.jpg",
        imageUrl_m: "http://images.amazon.com/images/P/0449005615.01.MZZZZZZZ.jpg",
        imageUrl_l: "http://images.amazon.com/images/P/0449005615.01.LZZZZZZZ.jpg",
        linkUrl:'/mens/0449005615',
        descreption:"Three men changed Seabiscuit's fortunes: Over four years, these unlikely partners survived a phenomenal run of bad fortune, conspiracy, and severe injury to transform Seabiscuit from a neurotic, pathologically indolent also-ran into an American sports icon."
      },

    ]
  }
  }
}